### ISSUE TITLE
Documentation: Parent/Child Context bean conflict handling

### ISSUE THREAD

**Issue by wcarmon** [Ekito/koin#101]
Navigate to https://insert-koin.io/docs/1.0/reference/contexts/  

This describes context nesting among other things.

Can you add explicit details for what happens when a parent & child context have a bean with the same type/class (a conflict).

Is the parent bean shadowed/ignored?  Is an exception thrown? ...

**Comment by arnaudgiuliani** [comment]
Doc for context/scope/modules will be reviewed totally. We are also thinking about having a better wording/dsl to express such need.

Keep in touch.

**Comment by arnaudgiuliani** [comment]
Check #143 for more info about new documentation
