### ISSUE TITLE
Documentation: logging

### ISSUE THREAD

**Issue by wcarmon** [Ekito/koin#102]
https://insert-koin.io/docs/1.0/reference/logging/

For posterity, can you add an example of how to replace the Logger (eg. `Koin.logger = AndroidLogger()`) or `EmptyLogger()`

**Comment by r03** [comment]
To integrate the logging with ktor and slf4j I did something like this:

This is the logger implementation:
```
import org.koin.log.Logger

class KoinLogger(private val logger: org.slf4j.Logger) : Logger {

    private val prefix = "(KOIN) :: "

    override fun debug(msg: String) {
        logger.debug(prefix + msg)
    }
    override fun err(msg: String) {
        logger.error(prefix + msg)
    }
    override fun log(msg: String) {
        logger.info(prefix + msg)
    }
}
```

Here is how I use it:
```
fun Application.init() {
    Koin.logger = KoinLogger(environment.log)
    startKoin(arrayListOf(KoinModule))

    install(DefaultHeaders)
    install(CallLogging) {
        level = Level.INFO
    }
    ...
```

**Comment by arnaudgiuliani** [comment]
You just need an implementation of `Logger` Koin class, and pass it to your `startKoin()`.

Doc will be updated for this.

**Comment by arnaudgiuliani** [comment]
Check #143 for more info about new documentation
