### ISSUE TITLE
Integration with Spek

### ISSUE THREAD

**Issue by OsQu** [Ekito/koin#105]
Lately I needed to integrate Koin with [Spek](http://spekframework.org/) and I could not find existing integration. Do you think it would be valuable to open a PR that implements similar implementation with Spek than the current integration with JUnit (https://github.com/Ekito/koin/blob/master/koin-test)? The integration would most likely live in `/koin-spek` folder to follow the existing integration conventions.

**Comment by arnaudgiuliani** [comment]
Hello,

yes, propose a PR on the base of `koin-test`module.

**Comment by arnaudgiuliani** [comment]
I close the issue here to continue on the PR
