### ISSUE TITLE
sharedViewModel is not available on a DialogFragment

### ISSUE THREAD

**Issue by rcraggs** [Ekito/koin#108]
Because sharedViewModel is defined as an extension of Fragment, it is not available within subclasses of Fragment such as DialogFragment.

This, for example makes it hard (for me) to get a view model with dialogs like TimePickers (https://developer.android.com/guide/topics/ui/controls/pickers.html)

https://github.com/Ekito/koin/blob/b957b5c4c63135d4713f7209da9889e39a310f4c/android/koin-android-architecture/src/main/java/org/koin/android/architecture/ext/LifecycleOwnerExt.kt#L36

**Comment by AkshayChordiya** [comment]
`DialogFragment` extends `Fragment` so technically extension functions on `Fragment` should be available to `DialogFragment`.
Make sure you are using `android.support.v4.app.DialogFragment` class

**Comment by rcraggs** [comment]
Thanks for the response. I was using a `android.app.DialogFragment` because I don't need to support that far back so with rather avoid the additional weight of the Support Libraries.

**Comment by arnaudgiuliani** [comment]
Yes, Architecture Components are only supported with support Fragments.

**Comment by arnaudgiuliani** [comment]
I close the issue then.
