### ISSUE TITLE
Injecting Named Dependencies within Constructor

### ISSUE THREAD

**Issue by jguerinet** [Ekito/koin#109]
Hello, 

Is there a way to inject a named dependency within a constructor? And if not, do you have a recommended way of doing this? 
Let's say I have the following: 
```
val myModule = applicationContext {
    bean("A") { MyComponent() } 
    bean("B") { MyComponent() }
    bean { MyOtherComponent() }
}
```
And I have an object that I is instantiated using constructor injection: 
``` 
class MyThirdComponent(val componentA: MyComponent, val otherComponent: MyOtherComponent) {
    ...
}
```
How would I specify which `MyComponent` I want in the `MyThirdComponent` constructor? I see in the docs how to specify which named component when injecting directly into other beans but not into a constructor. 

I see some potential workarounds: 
* Not use construction injection on `MyThirdComponent` and create a bean instead: 
```
val myModule = applicationContext {
    ...
    bean { MyThirdComponent(get("A"), get()) }
}
```
It defeats the purpose of constructor injection and requires two maintenance points (if I change the constructor of `MyThirdComponent` I would need to change the bean instantiation as well), but it could potentially work. 

* Inject what I can with the constructor, and then have `MyThirdComponent` extend `KoinComponent` and finish off the other injections with `by inject`: 
```
class MyThirdComponent(val otherComponent: MyOtherComponent) : KoinComponent {
    val componentA: MyComponent by inject("A") 
    ...
}
```
It's slightly more tedious but all of the injection is in one place and there's no need to create an unnecessary bean in this case. 

Am I missing something here/is there a better solution? If not, do you have any recommendations/thoughts on the above? I haven't tested any of these solutions yet, and I just started playing around with Koin today so this might be wrong... 
My apologies if this has been answered already, I searched the docs / issues and couldn't find anything on this subject. 

Merci! 
Julien

**Comment by Bodo1981** [comment]
I think you should go with the following solution:

```kotlin
class MyThirdComponent(val componentA: MyComponent, val otherComponent: MyOtherComponent) {
    ...
}
```

Declare all dependencies for your component as beans and **also your MyThirdComponent**
```kotlin
val myModule = applicationContext {
    bean("A") { MyComponent() } 
    bean("B") { MyComponent() }
    bean { MyOtherComponent() }
    bean { MyThirdComponent(get("A"), get()) } <-- provide your MyThirdComponent as bean
}
```

Then directly inject it in your class where you need your MyThirdComponent
```kotlin
class Foo : KoinComponent {
   val component: MyThirdComponent by inject() <-- directly inject it in your needed class
   ...
}
```

I think this should be the way to go. You are injecting the MyThirdComponent completely with your constructor. But you are wright. You have to change your bean creating if you change your constructor.

**Comment by arnaudgiuliani** [comment]
Hello @jguerinet, avoid using `KoinComponent` if you can. Try to always use constructor injection.

For you case, just use the `name` parameter as follow:

```kotlin
val myModule = applicationContext {
    bean("A") { MyComponent() } 
    bean("B") { MyComponent() }
    bean { MyOtherComponent(get("A"),get("B")) }
}
```

**Comment by jguerinet** [comment]
Hi @arnaudgiuliani  (and @Bodo1981), 

Thanks for your quick responses. It looks like option 1  is the way to to go!

**Comment by 100nandoo** [comment]
> Hello @jguerinet, avoid using `KoinComponent` if you can. Try to always use constructor injection.
> 
> For you case, just use the `name` parameter as follow:
> 
> ```kotlin
> val myModule = applicationContext {
>     bean("A") { MyComponent() } 
>     bean("B") { MyComponent() }
>     bean { MyOtherComponent(get("A"),get("B")) }
> }
> ```

What is the reason behind that? Does using KoinComponent have slower performance? Or maybe slower compile time?

**Comment by saket** [comment]
FYI `get()` was updated and accepts a `Qualifier` instead of a `String`. So the new solution would be:

```kotlin
MyOtherComponent(get(named("A")))
```
