### ISSUE TITLE
In case of `BeanInstanceCreationException`, clear resolution stack to avoid "Cyclic call while resolving $beanDefinition"

### ISSUE THREAD

**Issue by sofiaguyang** [Ekito/koin#110]
In the case of `BeanInstanceCreationException`, the bean definitions in the stack in `ResolutionStack` are not popped out. The next time I try to get a bean from the context, I get the error: `Cyclic call while resolving $beanDefinition`.

Thinking `BeanInstanceCreationException` must be caught to trigger the clearing of the stack and then re-thrown.

**Comment by arnaudgiuliani** [comment]
Fixed in `1.0.0-alpha-4`
