### ISSUE TITLE
ViewModel for generic classes

### ISSUE THREAD

**Issue by kiltonik** [Ekito/koin#1106]
In previous builds, probably some 2.xx there was an opportunity to obtain an instance of generic ViewModel by some code like the bellow one
`private val viewModel: ViewModel by viewModel(clazz)`
where 
`clazz: KClass<ViewModel>`
`ViewModel : BaseViewModel<Action, ViewState>`
I have recently update my project Koin dependency to the latest one and got an error
> Cannot use 'ViewModel' as reified type parameter. Use a class instead.

Have looked for any new ways to solve such a case, but have not found anything useful within the docs

 **Koin project used and used version (please complete the following information):**
```
    koin_version = '3.0.2'

    implementation "io.insert-koin:koin-android:$koin_version"
    implementation "io.insert-koin:koin-android-ext:$koin_version"
    implementation "io.insert-koin:koin-androidx-workmanager:$koin_version"
    testImplementation "io.insert-koin:koin-test-junit4:$koin_version"
```

Any help or useful links will be highly appreciated

**Comment by ivannr-kr** [comment]
I have this same issue currently trying to find a way around it. @kiltonik Looks like you posted this over a year ago, were you able to find a solution for this?
