### ISSUE TITLE
How reset injection

### ISSUE THREAD

**Issue by AndroFlo** [Ekito/koin#115]
Hello,
I have an Retrofit instance where it use a BASE_URL at the creation.
In my application before login, i can choose between two servers url. 
But the chnage cannot be applied.
So how can i deleted instance and restart it with modified url ?

Thank you

**Comment by AndroFlo** [comment]
I resolved my problem with this 
` StandAloneContext.closeKoin()`

**Comment by arnaudgiuliani** [comment]
Hello @AndroFlo, the `closeKoin` is here to drop all instances. It's quite radical but it works.
Else throw an eye  on contexts: https://insert-koin.io/docs/1.0/reference/contexts/

The idea is to isolate this kind of components with a limit life, in a context and drop it when you need.

**Comment by blundell** [comment]
@arnaudgiuliani does this still exist in koin 2? docs reference broke
