### ISSUE TITLE
No Thermosiphon

### ISSUE THREAD

**Issue by rongi** [Ekito/koin#116]
I've looked through the Koin 1.0.0 Roadmap and was concerned by the fact that there are no plans to add any Thermosiphon mentions to the Koin documentation. As DI library developers you know better than me, of course, that no DI library can be considered complete without a proper Thermosiphon mention. Is it just something that you forgot to write down or maybe it is just so obvious, that you don't think that it is necessary to bother yourself with adding the task? Thanks.

**Comment by arnaudgiuliani** [comment]
Hello @rongi,

Koin examples has been started. The coffee maker example is available here: https://github.com/Ekito/koin/tree/1.0.0/koin-projects/examples/coffee-maker

The koin-core example documentation will be updated about it.

**Comment by rongi** [comment]
![](https://i.giphy.com/media/XreQmk7ETCak0/giphy.webp)

**Comment by arnaudgiuliani** [comment]
Check #143 for more info about new documentation
