### ISSUE TITLE
Support AndroidX ViewModel

### ISSUE THREAD

**Issue by CristianGM** [Ekito/koin#122]
**Is your feature request related to a problem? Please describe.**
Google is changing the packaging to AndroidX, so, when we use Koin viewModel to do the injection it crashes with:
`Type parameter bound for T in inline fun <reified T : ViewModel> Context.viewModel(name: String = ..., noinline definition: Definition<T> /* = (ParameterProvider) -> T */): Unit
 is not satisfied: inferred type MyViewModel is not a subtype of ViewModel
e: ...`

**Describe the solution you'd like**
Allow to use androidx.lifecycle.ViewModel

**Describe alternatives you've considered**
hum... I don't think there are not a lot of alternatives

**Target Koin project**
android

**Comment by rosterloh** [comment]
Same issue here. I have to remove koin viewmodel injection until there is support or a workaround for this.

**Comment by arnaudgiuliani** [comment]
We need to create a new koin android project to let you use the androidx library and keep compat with old support lib.

We are on it. Stay tuned 👍

**Comment by DevHugo** [comment]
I have done the change for our use. It really not that big, just some import and one dependency to change in the build.gradle.

**Comment by arnaudgiuliani** [comment]
@mattmook have you made it from the `1.0.0` branch?

**Comment by mattmook** [comment]
@arnaudgiuliani no, but I have just reapplied the changes... https://github.com/mattmook/koin/tree/1.0.0

Assuming you are happy with the changes I can create a PR, as stated before I haven't yet because of the pre-release nature of androidx and android-p

**Comment by arnaudgiuliani** [comment]
Thanks @mattmook, I've just created the `koin-androidx` module - double check my changes with your changes. Just need a bit of time to test it and make deployment on bintray 👍

**Comment by arnaudgiuliani** [comment]
A first version is available under `koin-androidx`, version `1.0.0-alpha-10`.

**Comment by mattmook** [comment]
I see the other modules on bintray, but not `koin-androidx`. From what I remember of bintray new modules need to be explicitly linked to jcenter?

**Comment by arnaudgiuliani** [comment]
Argh ... yes :/ I need too link it to jcenter

**Comment by arnaudgiuliani** [comment]
Link to jcenter is made nightly I think.

**Comment by mattmook** [comment]
Looking at the updated `LifecycleOwner.getViewModelByClass`, with `this is Fragment` where `fromActivity` is true, should it read:

`ViewModelProvider(this.**activity.**viewModelStore, KoinFactory)`

**Comment by arnaudgiuliani** [comment]
Sorry, didn't push all the last sources. But, you're right it was a glitch from my part.

https://github.com/Ekito/koin/blob/1.0.0/android/koin-androidx/src/main/java/org/koin/android/architecture/ext/android/LifecycleOwnerExt.kt#L91

**Comment by mattmook** [comment]
Cool, thanks

**Comment by esqi** [comment]
I cannot found the library on the jcenter, is there any changes to the version?

**Comment by arnaudgiuliani** [comment]
note: package to check is `koin-androidx-scope` or `koin-androidx-viewmodel`

**Comment by stasbar** [comment]
I can't download packages
Failed to resolve: org.koin:koin-androidx:1.0.0-alpha-11
Failed to resolve: org.koin:koin-androidx-viewmodel:1.0.0-alpha-11
Failed to resolve: org.koin:koin-androidx-scope:1.0.0-alpha-11

**Comment by mattmook** [comment]
The first package is independent of androidx so is simply "org.koin:koin-android:$koin_version"
