### ISSUE TITLE
Use SLF4J as default logger

### ISSUE THREAD

**Issue by scottsteen** [Ekito/koin#130]
**Is your feature request related to a problem? Please describe.**
Having this as part of a production project isn't feasible without using a real logging implementation.

**Describe the solution you'd like**
An implementation of the koin Logger that uses SLF4J should be the default logger. If this isn't possible for Android apps, then could it be overriden as part of the android specific project?

**Describe alternatives you've considered**
Implementing my own is possible, but I'd prefer not to re-implement this in every project using Koin.

**Target Koin project**
koin-core (possibly also koin-android)

**Comment by erickok** [comment]
Please don't. It is trivial to implement Koin's `Logger` interface and there is no reason to have a dependency on any external logging library.

**Comment by scottsteen** [comment]
I did as you suggested, but Koin still prints some statements before my code to set the logger is executed. I'm building using Koin as part of a Ktor project, so don't have control over the program's entry point. Writing anything to stdout is dangerous, so the current implementation *could* be seen by many as a blocker to using such a great library.

Would you consider switching the default logger to Java Util Logging instead? Or even to have a service locator to allow me to change the logger by config, rather than programmatically?

**Comment by erickok** [comment]
Sure, I agree Koin should not log anything by default. cf #50

**Comment by arnaudgiuliani** [comment]
Koin is just providing a default way to Log. Each project has to define its way of logging.

For ktor & spark, we can provide a `koin-logger-slf4j` project implementation. I agree it's a missing part, but not a standard component from the core.

**Comment by arnaudgiuliani** [comment]
`koin-core` is not linked to any logging solution. Logging solution is a link from to your target runtime. For spark & ktor, it will be logged via slf4j. It's just a missing piece.

You can configure logging before starting Koin container, with `Koin.logger = <Your impl>`

Spring framework & Ktor are logging by default ... why koin logging should be a bad thing?

**Comment by arnaudgiuliani** [comment]
The point can be instead - log in debug level for the logging solution and let the user log it or not via its logging config.
