### ISSUE TITLE
[Koin 1.0] - Revamped DSL & new Module API

### ISSUE THREAD

**Issue by arnaudgiuliani** [Ekito/koin#131]
Hello,

we have revamped our Koin DSL to make it clearer. We can now declare our module like follow:

```kotlin
val myModule = module {
  single { ComponentA() }
  
  module("view"){
     single { ComponentB()}
  }
}
```

A Koin module (declared now with `module` function) can have an inner `module`. This DSL is more neutral and better target the idea of declaring module and inner modules.

The following keywords has been deprecated in favor of new ones:

* `applicationContext` -> `module`
* `context` -> `module`
* `bean` -> `single`

(`factory` has not been touched. You can still use `bean` keyword)

A module is declared in a `path`:

* `module { ... }` -> definitions are in `/`
* `module("app") { ... }` -> defintions are in `/app`
* `module("app.view") { ... }` -> defintions are in `/app/view`

Visibility rule is *child module can see parent module*. This mean that for module:

```kotlin
val myModule = module("app") {
  single { Repository() }
  
  module("view"){
     single { Presenter(get())}
  }
}
```

-> `Presenter` can see `Repository`.

You can now request a component with the optional `module` parameter, which indicates the required module path to lookup: `by inject(module="...")` or `get(module="...")`.

If you don't use the `module` parameter, you will lookup in all the modules as usual, else  you will lookup at given module path.

To request `Presenter` class, you can either write it `get<Presenter>()` or `get<Presenter>(module="app.view")`

The old `releaseContext` function has been renamed to `release`. If I want to release the `Presenter` instance, I can just use the module path: `release("app.view")`

This feature has been deployed in `1.0.0-alpha-8`. You can already check it and give us some feedbacks 👍

**Comment by phsavisiba** [comment]
Those keyword name changes are great and are now more natural with how other dependency injection libs name things.
