### ISSUE TITLE
ContextIsolation does not work well together with activityScope()

### ISSUE THREAD

**Issue by bmesing** [Ekito/koin#1314]
**Describe the bug**
When using activityScope() within an activity belonging to an isolated context, the app crashes on startup. Cause is, that lookup of the activity happens on GlobalScope `fun ComponentActivity.activityScope() = LifecycleScopeDelegate(this)`
Launching such an Activity crashes with `Unable to instantiate activity ComponentInfo{...DemoActivity}: org.koin.core.error.NoScopeDefFoundException: Scope 'q:'DemoActivity'' doesn't exist. Please declare it in a module.`

**To Reproduce**

```
abstract class BaseActivity : ScopeActivity() {
    override val scope: Scope by activityScope()
   ...
}

interface DemoKoinComponent : KoinComponent {
    override fun getKoin(): Koin = koinApp!!.koin
    companion object {
        var koinApp : KoinApplication? = null
    }
}

class DemoActivity : BaseActivity(), DemoKoinComponent {
...
}
```
somewhere executed before launching DemoActivity:

```
   fun startKoin() {
        DemoKoinComponent.koinApp = koinApplication {
            modules(
                module {
                    scope<DemoMakePaymentActivity> {}
                }
            )
        }
    }
```
Now launching DemoActivity somewhere crashes with `Unable to instantiate activity ComponentInfo{...DemoActivity}: org.koin.core.error.NoScopeDefFoundException: Scope 'q:'DemoActivity'' doesn't exist. Please declare it in a module.`

Also it is not easy to create a workaround for this, because `LifecycleScopeDelegate` takes a `KoinContext` as input parameter (though it only uses `Koin`). Otherwise this could be easily fixed by changing

````
fun ComponentActivity.activityScope() = LifecycleScopeDelegate(this)
````

to 

```
fun ComponentActivity.activityScope() {
    val koin = if (this is KoinComponent) {
        this.koin
    } else {
        GlobalContext.get()
    }
    return LifecycleScopeDelegate(lifecycleOwner = this, koin = koin)
}
```
Since `KoinComponent` and `KoinContext` are different types I cannot pass the `KoinComponent` into `LifecycleScopeDelegate()` even though what it needs would be just a `Koin`

Suggested fix would be to provide a constructor for `LifecycleScopeDelegate`, which creates it with a `Koin` instead of a `KoinContext`.

**Expected behavior**
Should not crash but work.

**Koin project used and used version (please complete the following information):**
 `koin-core version 1.3.2`

**Comment by bmesing** [comment]
For the record: with koin 1.3.5 LifecycleScopeDelegate does support passing koin as parameter, so our local workaround for this problem is to create:

```
private fun getKoin(activity : ComponentActivity) : Koin{
    return if (activity is KoinComponent) {
        activity.getKoin()
    } else {
        GlobalContext.get()
    }
}

fun ComponentActivity.contextAwareActivityScope() = LifecycleScopeDelegate<Activity>(
    lifecycleOwner = this,
    koin = getKoin(this)
)
```

And use contextAwareActivityScope() instead of activityScope()

**Comment by arnaudgiuliani** [comment]
Are you using the latest version?

in 3.1.5 The LifecycleScopeDelegate looks like:

```kotlin
class LifecycleScopeDelegate<T>(
    val lifecycleOwner: LifecycleOwner,
    private val koin: Koin,
    private val createScope: (Koin) -> Scope = { koin: Koin ->
        koin.createScope(
            lifecycleOwner.getScopeId(),
            lifecycleOwner.getScopeName(),
            lifecycleOwner as T
        )
    },
)
```

We pass the right Koin instance to it. But sill looking on my side about combined Scope/SDK ...

**Comment by arnaudgiuliani** [comment]
In latest Koin version I could work with isolated SDK and Scope:


```kotlin
class HostActivity : ScopeActivity(), CustomKoinComponent {

    // Inject by Interface - default definition
    val sdkService: SimpleService by inject()
    val sdkSession : Session by inject()
```

```kotlin
object CustomSDK {
    val koinApp = koinApplication {
        modules(sdkModule)
    }
}

val sdkModule = module {
    single<SimpleService> { SimpleServiceImpl() }

    scope<HostActivity>{
        scoped { Session() }
    }
}
```

**Comment by arnaudgiuliani** [comment]
You can find the complete sample: https://github.com/InsertKoinIO/koin/blob/main/examples/androidx-samples/src/main/java/org/koin/sample/androidx/sdk/HostActivity.kt
