### ISSUE TITLE
Support for androidx package

### ISSUE THREAD

**Issue by vincent-paing** [Ekito/koin#138]
Since 28 sdk become final, it won't be long until 28 support lib will be stable too. After that, Support package naming will be deprecated and androidx naming will be favoured. Currently Koin is still using old package name. It would be better if it's made future-proof by renaming to androidx lifecycle in next release

**Comment by arnaudgiuliani** [comment]
Hello @vincent-paing,

Koin `1.0.0` will bring a dedicated androidx package. We have begun the `koin-androidx` package:
https://github.com/Ekito/koin/issues/122

Stay tuned for next news
