### ISSUE TITLE
Inject to non android classes.

### ISSUE THREAD

**Issue by sankarsana** [Ekito/koin#139]
Thanks to the developers for this library!

Is the ability to do something like this?:

```
object Logger {
    private val writer: Writer by inject()
    ...
}
```

**Comment by arnaudgiuliani** [comment]
Hello @sankarsana,

just add the `KoinComponent` interface to your class.

```kotlin
object Logger  :  KoinComponent {
    private val writer: Writer by inject()
    ...
}
````

**Comment by sankarsana** [comment]
So simple!!!
Thanks for the quick response.
I think this should be written in the documentation. Maybe I did not find it?

**Comment by arnaudgiuliani** [comment]
Current version of the documentation is here: http://insert-koin.io/docs/1.0/reference/koin-dsl/

We are rewriting it for the 1.0

**Comment by sankarsana** [comment]
Thank you!
