### ISSUE TITLE
Pre-loading heavier modules

### ISSUE THREAD

**Issue by jmiecz** [Ekito/koin#141]
Hello,

Is there a way to pre-load some modules? I've noticed that the UI thread will sometimes lock up for a couple of seconds while Koin is grabbing all the depenicies. 

An example would be, having an HttpClient that is used among different services. When you call on the first service, the app will hang while it creates the HttpClient for the 1st time but any calls after will result in 0 delay.

**Comment by arnaudgiuliani** [comment]
Hello @jmiecz,

not available in last 0.9.x version.

For `1.0.0` release, the `eager` parameter will be added to definitions & modules, to allow a definition/module to be created at start.

**Comment by jmiecz** [comment]
@arnaudgiuliani Do you happen to have an ETA of when 1.0.0 will drop?

**Comment by arnaudgiuliani** [comment]
Target `1.0.0` release is for September.

There will be some beta versions before.

**Comment by jmiecz** [comment]
Cool, thanks @arnaudgiuliani ! 

Side question, will `eager` help with the frame skipping?

**Comment by arnaudgiuliani** [comment]
Frameskip comes from processing in main thread. 

Preloading stuff and make load in background thread will help you 👍

**Comment by jmiecz** [comment]
Sounds good, thanks :D

**Comment by johnnycube** [comment]
> make load in background thread will help you

How is it possible to load Koin dependencies in the background thread? Something that can be accomplished with Coroutines or RX?

**Comment by arnaudgiuliani** [comment]
@johnnycube all definitions are lazy by default. We are currently working on the `eager` tag.

We will have:
- a `createEagerInstances` boolean parameter from `startKoin()` to directly create eager definitions at start
- a `createEagerInstances()` function to call, to create eager instances when you want (and when you don't to create it directly at start)

You will be able to use this last in a background thread.

**Comment by arnaudgiuliani** [comment]
available in koin `1.0.0-alpha-18`
