### ISSUE TITLE
License is not valid

### ISSUE THREAD

**Issue by stephanenicolas** [Ekito/koin#15]
Hi @arnaudgiuliani,

I just looked into your DI lib and I noticed you license file is missing your name and the year, which makes it invalid. 

But, this details, apart. I would be interested in chatting with you if you are interested. I am one of the authors of [toothpick](https://github.com/stephanenicolas/toothpick/) and I would like to understand better a few things about the way kotlin and koin work. I would have written an email to you but I couldn't find it on the net. Mine is much either to find. If you are interested, just send me an email.

Cheers,
 S.

**Comment by arnaudgiuliani** [comment]
Hi @stephanenicolas,

Thanks. I've just updated it.

Interested in chatting with you about Koin and Kotlin. I've only found your g+ profile.
I'll try to send you an email.
