### ISSUE TITLE
Context is not available for modules loaded in library

### ISSUE THREAD

**Issue by StephaneBg** [Ekito/koin#164]
Koin version is 1.0.0-beta-3.

I have a library inside my project that loads its own modules with loadKoinModules().
The application calls startKoin() with its own reference. All the modules have the same path.

In my application:
` startKoin(this, listOf(fisrtModule, secondModule))`

In my library:
`loadKoinModules(libFirstModule, libSecondModule)`

I expect that the Context provided in startKoin() would be available for all modules. But I get this error:
`org.koin.error.BeanInstanceCreationException: Can't create definition 'Factory [class='fr.toto.Presenter']' due to error : No compatible definition found for type 'android.app.Application'. Check your module definition`

I then tried to provide the Context when I load the modules from the library:
`loadKoinModules(libFirstModule, libSecondModule) with application`

But this time I get an other error because the Context is overridden:
`org.koin.error.BeanOverrideException: Try to override definition Single [class='android.content.Context'] with Single [class='android.content.Context'], but override is not allowed. Use 'override' option in your definition or module.`

Why the Context is overridden whereas it is not defined?

Thanks a lot.

**Comment by arnaudgiuliani** [comment]
Hi @StephaneBg,

that's because we refactored the `startKoin()` to use `Context` instance and not `Application` anymore. I think you try to resolve `Application` instance from one of your modules. You should use the `Context` instance instead.

And the `with` operator doesn't override default definition.

**Comment by arnaudgiuliani** [comment]
Try to use `androidContext()` in your module to retrieve current `Context` instance.
