### ISSUE TITLE
Inject support for BroadcastReceiver

### ISSUE THREAD

**Issue by dkrivoruchko** [Ekito/koin#17]
Hi, thanks for the great lib. 
Please add inject support for android.content.BroadcastReceiver.
Thanks.

**Comment by Baresse** [comment]
Hi @dkrivoruchko 

You can do it this way today :  

> val presenter = StandAloneContext.koinContext.get<LoginContract.Presenter>()

Doing so you are hacking the lib. But in the next version you should be able to do it more properly.

**Comment by dkrivoruchko** [comment]
Thanks!

**Comment by Baresse** [comment]
More detailed answer can be found here : https://github.com/Ekito/koin/issues/7#issuecomment-342953113

**Comment by caleb-allen** [comment]
Is there a more correct way to do this in 0.8.2? Looks like the `get` method was removed from the `StandAloneContext` interface, so right now I've gotten it working with:

`val service = (StandAloneContext.koinContext as KoinContext).get<MyService>()`

**Comment by arnaudgiuliani** [comment]
Tag your class with `KoinComponent` interface. You will be able to inject as you were in an Activity.
