### ISSUE TITLE
FragmentStatePagerAdapter injection

### ISSUE THREAD

**Issue by pbayburtyan** [Ekito/koin#20]
Hi guys, I need some help with injecting of state pager adapter.  
I do it like this now:

```
class AppModule : AndroidModule() {
    override fun context() = applicationContext {
        context(name = CTX_CANVAS_ACTIVITY) {
            provide { MainPagerAdapter(getProperty(MainActivity.FRAGMENT_MANAGER_KEY), getProperty(MainActivity.FRAGMENT_NAMES_KEY)) }
```

And in `MainActivity`

```
private val pagerAdapter by inject<MainPagerAdapter>()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        getKoin().setProperty(FRAGMENT_MANAGER_KEY, supportFragmentManager)
        getKoin().setProperty(FRAGMENT_NAMES_KEY, resources.getStringArray(R.array.main_view_pager_items))
```

However after orienation change I get an `IllegalStateException` like no fragment for the key. What is the right way to do such injection? Thanks in advance.

**Comment by Obaied** [comment]
Where's the IllegalStateException occurring exactly?
Also, can you paste the logcat output of the exception?

**Comment by arnaudgiuliani** [comment]
In the 2nd snippet, you are registering new properties. Why making `supportFragmentManager` as a property ? I do not encourage to extract Android specific components like that. Try to write all things that are injected with Koin as less coupled possible with Android world.

**Comment by pbayburtyan** [comment]
Hi guys. Thanks a lot for your answers. Actually I made a stupid mistake: I just forgot to call `releaseContext` in the activity. 
@arnaudgiuliani could you please  what is the better way to provide `supportFragmentManager` for the pager?

**Comment by arnaudgiuliani** [comment]
I think, we do it usually without any DI. We get it from our last activity.
My advice is to be very careful with injection against Android component system. avoid make it with Koin if possible. The thing that I don't know well is: is the supportFragmentmanager entirely stateless. If this is the case, you could pass it by a property. But avoid any risk of keeping any reference to a component that couldn't be garbaged
