### ISSUE TITLE
New scope between factory and single - better ScopedWith() shared instances

### ISSUE THREAD

**Issue by Narayane** [Ekito/koin#203]
Hi,

First, thank you so much for your amazing work :)

I would like to have a new scope between _factory_ and _single_ which would be similar to scope [**Shared**](https://github.com/AliSoftware/Dip/wiki/scopes) in **Dip**, the DI framework I use in my iOS/Swift stack.

To be brief, it is as if a class instance with _factory_ scope acts like a class instance with _single_ scope while it is referenced by at least one dependency graph.

With it, I could share a class instance between multiple others class instances (Koin guaranteeing me its uniqueness) without declare it  as a "singleton" from "memory management" point of view...

Cheers

**Comment by arnaudgiuliani** [comment]
Interesting proposal 👍
