### ISSUE TITLE
Injecting mocks

### ISSUE THREAD

**Issue by Obaied** [Ekito/koin#22]
I was wondering if its possible to inject custom mocks to a class overloaded with `KoinComponent`?

So a class like `MyViewModel.kt`:
```
class GridViewModel
    : ViewModel(), KoinComponent {
    private val postRepository by inject<PostRepository>()
...
}
```

would have `postRepository` to be injectable when writing a test as such
```
class GridViewModelTest : KoinTest {
    lateinit var mockPostRepository: PostRepository
    lateinit var gridViewModel: GridViewModel

    @Before
    fun init() {
        mockPostRepository = mock()

        // Basically have `mockPostRepository` to be the injected postRepository from Koin
        gridViewModel = KoinInjector<GridViewModel>(mockPostRepository)
    }
}
```

Any idea how to do such a task?

Much appreciated!

**Comment by Obaied** [comment]
Ok this is embarrassing, but I found a solution. I'll post it here to safely close the issue.

P.S: I think its worth putting it in the README since I don't think its mentioned.

```
class GridViewModelTest : KoinTest {
    lateinit var mockPostRepository: PostRepository
    val gridViewModel by inject<GridViewModel>()

    @Before
    fun init() {
        mockPostRepository = mock()
        startKoin(testAppModules())
    }

    fun testAppModules() = listOf(TestApplicationModule())
    inner class TestApplicationModule : AndroidModule() {
        override fun context() = applicationContext {
            provide { mockPostRepository } bind (PostRepository::class)
            provide { GridViewModel() }
        }
    }
}

```

Steps are as follows:
- Make the test Inherit from `KoinTest`
- Make an inner module that extends `AndroidModule()`. We'll use this to inject the mock dependencies and initialise the classes that depend on them.
- in your `@Before` flagged function, initialise all the mocks and run `startKoin(testAppModules())` where `testAppModules` are your list of test modules.
- Now when `startKoin()` is invoked, the real objects would use the mock dependencies.

Cheers!

**Comment by arnaudgiuliani** [comment]
No problem :)
