### ISSUE TITLE
provide(isSingleton = true)

### ISSUE THREAD

**Issue by spleenware** [Ekito/koin#28]
I am trying to share a presenter between an Android Activity and a Fragment, and am using ContextAwareActivity/ContextAwareFragment, with the same context name. However, the 'by inject' of the presenter object is creating multiple instances (even though I'm specifyig isSingleton in provide).

**Comment by arnaudgiuliani** [comment]
Hello,

by default, every bean that you declare with `provide { }` is a singleton. But, using ContextAware components help you automatically drop the configured context. To share a presenter, declare it in a context:
```Kotlin
context("YourContext"){
    provide { MyPreenter() }
}
```
Inject in into your Fragment and Activity. But, the context have to be dropped by the last component, tied to your context: the activity. Only your activity has to be ContextAware.

To better understand, try to make it without ContextAware* component and just call `releaseContext(/* your context name */)` from `onPause` or `onStop`in your Activity.

Hope this is a bit clearer for you.

**Comment by spleenware** [comment]
OK, thanks.  I just made my Fragment a normal one, instead of ContextAware,
and works fine now.
I didn't realise the ContextAware stuff did the release

**Comment by spleenware** [comment]
Also, what is the recommendation way to have inject() retain an instance,
eg. a Presenter, across an Android config change (like device rotation)?
ie. to prevent the usual release in these cases.

**Comment by arnaudgiuliani** [comment]
To retain things over rotation, you must use Koin properties: Inject & set your data to retain as properties, it will be available as long as the application is alive. I'm preparing an article about that pattern point for next weeks.
