### ISSUE TITLE
Not possible to add non-Android module to Android Koin

### ISSUE THREAD

**Issue by Alviere** [Ekito/koin#29]
Hi there! Thanks for your hard work on Koin! Great library.
Anyway, I faced an issue, where you force to provide list of `AndroidModule`'s to `Application.startKoin()`. Thus it is impossible to provide modules that are built, for example, in data or domain layers, which are usually written without platform dependencies.
Briefly looking through your code, I haven't found any serious reason to force `AndroidModule` for `android` artifact. What do you think? This will be a big win, if your `android` artifact's `startKoin` function will accept all descendants of `Module`.

**Comment by arnaudgiuliani** [comment]
Hello,

Koin 0.7.0 brings a better DSL and Koin modules won't have any dependency with Android classes. Up to you to inject Application/Context dependencies or not.

The `startKoin()` from 0.7.0 will accept `Modules` as you pointed, allowing to build fully independent modules for Android.

Wait the next days, for the next release  (hope to release it before xmas :) )

**Comment by Alviere** [comment]
Great news!
BTW, could you specify a bit how the system will behave in that way. Are non android modules will be bound to application? Or they will live forever?
And how I understand it, sub context dependencies will still be able to cleared even if they are not in android module, right?

**Comment by arnaudgiuliani** [comment]
`AndroidModule` only give you some shortcuts to inject Application instance (the androidApplication property). this will be available again, with a classic injection (`get()`)

Sub context is a core feature. You can drop context even if you are not in an Android app.

**Comment by arnaudgiuliani** [comment]
You can check the Koin 0.7.1 on https://insert-koin.io
