### ISSUE TITLE
Is there inject resolution collision in sub contexts

### ISSUE THREAD

**Issue by TonicArtos** [Ekito/koin#31]
What happens if two sub contexts both have beans which satisfy an inject request?

```kotlin
val KoinModule = applicationContext {
  context("foo") {
    provide { wombat() } bind Animal::class
  }

  context("bar") {
    provide { koala() } bind Animal::class
  }
}

class Pojo {
   val animal: Animal = inject() 
}
```

**Comment by arnaudgiuliani** [comment]
Hello,

if you try to resolve `Animal` type you will have a conflict: Koin doesn't know on which instance definition to go. 

Context is there to help against visibility (parent/child) and to be dropped later if needed.

I think you have to think about 2 possible ways : 
- provide definition with a name : `provide("wombat") { wombat() } bind Animal::class`
- use a factory and pass argument to it

If you provide a definition with a name, use it when you inject: `val animal: Animal by inject("wombat") `

Last point, your class Pojo can't be injected like that. You should write it:

```kotlin
class Pojo : KoinComponent {
   val animal: Animal by inject() 
}
```
