### ISSUE TITLE
Error:Failed to resolve: org.koin:koin-android-architecture:0.8.0

### ISSUE THREAD

**Issue by fredy-mederos** [Ekito/koin#34]
Hi, I updated my project to koin 0.8.0 in order to try the new koin-android-architecture module but gradle can't resolve it.

Error:Failed to resolve: org.koin:koin-android-architecture:0.8.0

My gradle file:
```
implementation "org.koin:koin-android-architecture:$koin_version"
```
It seems koin-android-architecture isn't available in jcenter

**Comment by arnaudgiuliani** [comment]
Hello,

exactlty, we have an issue for publishing to bintray/jcenter (but I've begin to publish the doc for 0.8.0). While I'm waiting for an answer from Jfrgog, you can add the following repository to use `koin-android-architecture`:

```gradle
repositories {
    maven {
        url  "https://dl.bintray.com/ekito/koin" 
    }
}
```

**Comment by fredy-mederos** [comment]
Thanks a lot.
Let me know when the issue is done

**Comment by arnaudgiuliani** [comment]
Hope to see it on jcenter quickly :)

**Comment by arnaudgiuliani** [comment]
Package is on jcenter
