### ISSUE TITLE
Version 0.8.0 misses on jcenter for koin-ktor

### ISSUE THREAD

**Issue by Hikaru755** [Ekito/koin#38]
Trying to setup my project, gradle failed to resolve the koin-ktor dependecy. Looking at the jcenter index, it seems like koin-ktor is the only coin module missing the stable 0.8.0 version missing, as evidenced here: https://jcenter.bintray.com/org/koin/koin-ktor/

**Comment by arnaudgiuliani** [comment]
Hello,

I pushed the 0.8.0 again for koin-ktor
