### ISSUE TITLE
Koin cannot instantiate bean with enum inside

### ISSUE THREAD

**Issue by evelyne24** [Ekito/koin#41]
Hi,

I am getting the following error:

```
Caused by: org.koin.error.BeanInstanceCreationException: Can't create bean Factory[class=com.myapp.ui.register.RegisterViewModel, binds~(android.arch.lifecycle.ViewModel)] due to error :
                  	java.lang.IllegalArgumentException: Invalid data. Unsupported type: com.myapp.data.User$Status (found in field status)
```

`User`is a data class that has an `enum` of type `Status`

Any ideas what to do?

**Comment by arnaudgiuliani** [comment]
Hello,

seems it can't instantiate your bean :/ Can you give your module definition and the Kotlin code of the component?

**Comment by arnaudgiuliani** [comment]
@evelyne24 Still here ?

**Comment by arnaudgiuliani** [comment]
Please reopen the issue if needed. 

Thanks.

**Comment by trustmub** [comment]
i am having the same challange with my ptoject. please check it on GitHub is a https://github.com/trustmub/blueprint
