### ISSUE TITLE
[Contributor needed] UI testing with ViewModels

### ISSUE THREAD

**Issue by dGorod** [Ekito/koin#48]
Hello, @arnaudgiuliani !

Thank you for a great DI library.  Starting using it and need some help with testing. 

I have Android project with architecture components. I inject ViewModel using lazy 'by viewModel()' method. Inside ViewModel I have a repository that goes to API. Now I want to write UI tests for my app using Espresso. Obviously, I don't need real calls to the Internet, I want mocked data returned using Mockito. 
And now I'm confused in what direction I should go. I read [article about testing](https://insert-koin.io/docs/1.0/getting-started/junit-test/) in documentation. But still can't figure out how to inject mocked repository inside my ViewModel for Espresso test.

Will appreciate any help.
Thanks.

**Comment by dGorod** [comment]
Test project where want to try it first: https://github.com/dGorod/test_500px_api_kotlin

**Comment by arnaudgiuliani** [comment]
Hello,

this is one the `hot` topics for Koin. Anybody with `Espresso` knowledge is welcome to give help for Koin 👍

The article you mention deals about unit testing (testing before the UI) - Which is (in my point of view) essential to do before making any UI test.

I'll put that on top priority.

**Comment by mataiaslev** [comment]
Hi,

For insert mock objects under Espresso I am essentially configuring the tests for use another "Application" class for start. That use another startKoin(..) method, that calls our TestModules in place of the modules for the Real app. (This imply make some methods open, and probably will be improved.)

**Configurations and Code:**

**Gradle:**
```
defaultConfig {
        testInstrumentationRunner 'com.your.path.CustomInstrumentationTestRunner'
        ...
}
```

and I add the library androidTestCompile 'com.linkedin.dexmaker:dexmaker-mockito:2.12.1'
 for let mockito do his job in this context.

**Custom AndroidJUnitRunner under the folder of the espresso tests:**
```
class CustomInstrumentationTestRunner: AndroidJUnitRunner() {

    @Throws(InstantiationException::class, IllegalAccessException::class, ClassNotFoundException::class)
    override fun newApplication(cl: ClassLoader,
                                className: String,
                                context: Context): Application {
        return Instrumentation.newApplication(MyIntegrationTestApp::class.java, context)
    }

}
```

**Our application for tests:**

```
class MyIntegrationTestApp: MainApplication() {
    override fun onCreate() {
        super.onCreate()
        val testModule = TestModule()
        val authenticator = Mockito.mock(Authenticator::class.java)
        Mockito.`when`(authenticator.isAuthenticated()).thenReturn(true)
        testModule.authenticator = authenticator
        startKoin(this, listOf(testModule))
    }
}
```
My **TestModule** looks like:

```
class TestModule: AndroidModule() {
    lateinit var authenticator: Authenticator

    override fun context() = applicationContext {
        context(name = "MainActivity") {
            provide { context }
            provide { authenticator }
            provide { AuthUIWrapper() }
            provide { ActionIntentGenerator(get(), get()) }
            provide { AuthViewModel(get(), get()) }
            provide { FirebaseAuth.getInstance() }
            provide { Screen(get()) }
            provide { PetFactory(get()) }
            provide { MutableLiveData<List<Pet>>() }
            provide { PetHelper() }
            provide { PetAdapter() }
            provide { FirebaseFirestore.getInstance() }
            provide { PetViewModel(get(), get(), get()) }
            provide { FirestorePetRepository(get(), get()) } bind PetRepository::class
        }

    }
}
```

So, I can set the **Authenticator** with the mock I want for the Espresso tests.

**# RELATED TO THE UNIT TESTS:**

What I do is create a TestModule: (Extends for Module and not for AndroidModule in this context) and the I startKoin into the tests with this modules.

```
class MyTestModule: Module() {

    lateinit var petRepository: PetRepository
    lateinit var petFactory: PetFactory
    lateinit var petHelper: PetHelper

    override fun context(): Context = applicationContext {
        provide { petRepository }
        provide { petFactory }
        provide { petHelper }
    }
}
```

Test example: we are using startKoin on koin context, just need the list of modules.
```
"PetViewModel should fetch data from the pet repository, when solicited data" {
            val testData: LiveData<List<Pet>> = MutableLiveData()
            val repository = Mockito.mock(PetRepository::class.java)
            val petFactory = Mockito.mock(PetFactory::class.java)

            val myTestModule = MyTestModule()
            myTestModule.petRepository = repository
            myTestModule.petFactory = petFactory

            startKoin(listOf(myTestModule))

            val petViewModel = PetViewModel()
            `when`(repository.getAllPets()).thenReturn(testData)

            val data = petViewModel.getAllPets()

            verify(repository).getAllPets()
            data shouldBe testData
        }
```
I am using kotlintest. And I can insert mocks :)

Thanks for all, And tell me please if something is not clear. I have experience in development but I am very new sharing my knowledge hahaha so Just tell me and I can improve :)

**Comment by arnaudgiuliani** [comment]
Interesting 👍

**Comment by cyberratt** [comment]
You could just change your myTestModule, for instance instead of assigning a mock to the petRepository, just changes the provide method to a  'mock(PetRepository::class.java) as PetRepository' or if you're using  mockito-kotlin just mock<PetRepository>()

**Comment by arnaudgiuliani** [comment]
In fact, Koin is already compatible with Android instrumented espresso tests. Just need precise explanation on what and how to do things

**Comment by arnaudgiuliani** [comment]
Instrumented test are compatible `as is` with Koin. I will document it

**Comment by arnaudgiuliani** [comment]
You can find espresso/room tests in https://github.com/InsertKoinIO/koin/tree/1.0.0/koin-projects/examples/android-mvvm/src/androidTest/java/fr/ekito/myweatherapp

Just use the `KoinTest` interface to tag your test class and use Koin features. The espresso test will use the default Koin configuration from your application. You can then override definitions to help you make your tests.

A good article https://proandroiddev.com/testing-with-koin-ade8a46eb4d

**Comment by cynw** [comment]
In addition to @mataiaslev answer, my project is using `MockMaker` mockito extension to run unit test.
I got this compile error
```
More than one file was found with OS independent path 'mockito-extensions/org.mockito.plugins.MockMaker'
```
To fix this error, add exclude `group: 'org.mockito'` to the dependency in the gradle file.
```
androidTestImplementation("org.koin:koin-test:1.0.2:") { exclude group: 'org.mockito' }
```
