### ISSUE TITLE
Bean implements multiple interfaces. How to inject only some of them? 

### ISSUE THREAD

**Issue by dkrivoruchko** [Ekito/koin#55]
There is a case:
`interface Repo {
interface RO {}
interface RW: RO {}
}`

`bean { RepoImpl() as Repo.RW}`

`class UserCaseA(val repoRW: Repo.RW)`
`bean {UseCaseA(get())}` - Works

`class UseCaseB(val repoRO: RepoRO)`
`bean {UseCaseB(get())}` - Fails. It's clear why is fails.

But is there any simple way to get it's working?
The main point is to create and keep only ONE instance of RepoImpl().

**Comment by arnaudgiuliani** [comment]
Hello,

`bean` is a shortcut for `provide` keyword, but with restricted options. For more complete provided definitions, we must go back with `provide`. In your case, you should declare your bean with:

`provide { RepoImpl() as Repo.RW } bind Repo.RO::class`

This will allow binding on `Repo.RW` and `Repo.RO`

**Comment by dkrivoruchko** [comment]
Thanks!
