### ISSUE TITLE
Cannot resolve viewModel injection with delegate style declaration

### ISSUE THREAD

**Issue by shrpereira** [Ekito/koin#56]
I'm trying to follow the documentation using delegate style declaration of ViewModels but I cannot resolve the import in Android Studio.
<img width="917" alt="screen shot 2018-02-16 at 18 05 14" src="https://user-images.githubusercontent.com/1263771/36326989-2c6b39a2-1344-11e8-97de-90a52624cc8c.png">

This is my code:
![screen shot 2018-02-16 at 18 07 08](https://user-images.githubusercontent.com/1263771/36327002-3f46b16e-1344-11e8-982c-89a1699de0e1.png)

What I'm doing wrong? Any advice is appreciated.

**Comment by fredy-mederos** [comment]
Your code looks good to me.
Are you shure you are compiling koin-android-architecture 0.8.2 ??
```gradle
// Koin for Android Architecture Components
compile "org.koin:koin-android-architecture:0.8.2"
```

**Comment by caleb-allen** [comment]
Are you importing correctly?

    import org.koin.android.architecture.ext.viewModel

**Comment by caleb-allen** [comment]
Maybe try declaring the type in the value?

    val myViewModel : MyViewModel by viewModel()

**Comment by shrpereira** [comment]
The problem was the version I was using, 0.8.0. But now that I was able to import, there's another problem:

<img width="593" alt="screen shot 2018-02-16 at 21 56 32" src="https://user-images.githubusercontent.com/1263771/36335051-5fa2dae4-1364-11e8-816d-b79ec5d8c72e.png">

Do you guys know how should I proceed? I really like to get the viewModel instance inside my BaseActivity to handle snackbar, toast and other generic observers from my ViewModel.

**Comment by caleb-allen** [comment]
You don't need the angle brackets for the viewmodel I believe

**Comment by caleb-allen** [comment]
Scratch that I misunderstood that your activity was generic

**Comment by arnaudgiuliani** [comment]
Hello,

we can't use generic type `T` with infered Kotlin parameter :/

Best thing is to add a method to allow such declaration: `val myViewModel : MyViewModel<T> by viewModel(T::class)` or something like that.

**Comment by shrpereira** [comment]
What I trying to do is receive the type of View Model as parameter and inject a new instance of this type. There's no MyViewModel. The ViewModel types would be received in a generic way. The problem is because it's an inline function with reified type, it's not allowed to receive the type like we have here. 

I'm going to try to strip the injection source code and implement a ViewModelFactory to initialize it inside the BaseActivity but this would not benefit from the rest of the library features

**Comment by shrpereira** [comment]
After 2 days I had no success trying to make this work.
I'm having a hard time working with generics in kotlin, something I could do in Java very easily.
I don't want to try another libraries for dependency injection but since I'm in the beginning of a new project in the company I work for, if I can't solve this quickly I'll be forced to try another libs or maybe, write this in Java.

**Comment by caleb-allen** [comment]
Does
    val myViewModel : T by viewModel()

Not work?

**Comment by arnaudgiuliani** [comment]
Yes Ok. Sorry there was a mistake in my answer. 
You need to write:

`val model: T by viewModel(T::class)` or `val model: T by lazy {getViewModel(T::class)}`

Let me write a patch 👍

**Comment by arnaudgiuliani** [comment]
fix is available in current alpha: `0.9.0-alpha-11`

**Comment by arnaudgiuliani** [comment]
API has been updated to have `val model: T by viewModel(<KClass<T>>)` and avoid reified types this way.

Your base activity must be like:

```kotlin
class Base Activity<T : ViewModel>(clazz : KClass<T>){
    val model : T by viewModel(clazz)
}
```
We can't pass reified parameters from class.

**Comment by shrpereira** [comment]
It worked! Thanks very much!!! I'll try make an extension or something like that to avoid having to pass the class as a parameter but for now, that's working wonderfully!!

**Comment by arnaudgiuliani** [comment]
Cool :) I close the issue.

**Comment by Nekromancer** [comment]
@shrpereira Did you manage to avoid having to pass the class as a parameter?

**Comment by arnaudgiuliani** [comment]
@shrpereira  You will be able to get viewModel by class with `viewModelByClass()` and `getViewModelByClass`. This is the final version of the API fir release `0.9.0`

**Comment by fathallah92** [comment]
@shrpereira Have you added an extension to not class as a parameter to the activity ?

**Comment by shrpereira** [comment]
@fathallah92 
No. I've used the following approach:
* I have a BaseActivity:
```
open class BaseActivity<out ViewModelType : BaseViewModel>(clazz: KClass<ViewModelType>) :
        AppCompatActivity() {

    val viewModel: ViewModelType by viewModel(clazz)
}
```

* And on each activity, I pass the viewModel class like this:
```
class MainActivity : BaseActivity<MainViewModel>(MainViewModel::class) {}
```

But I'm not coding on this project for some time (it's in production, though), so, probably there are better ways to do it.

**Comment by LoAlex** [comment]
@arnaudgiuliani 
Are there any elegant approach that not pass class as a parameter to the activity?

**Comment by ductranit** [comment]
> @arnaudgiuliani
> Are there any elegant approach that not pass class as a parameter to the activity?

Hope this isn't too late. You can try this:
```

open class BaseFragment<M : ViewModel> : Fragment() {
    val viewModel: M by lazy { getViewModel(viewModelClass()) }

    @Suppress("UNCHECKED_CAST")
    open fun viewModelClass(): KClass<M> {
        // dirty hack to get generic type https://stackoverflow.com/a/1901275/719212
        return ((javaClass.genericSuperclass as ParameterizedType)
            .actualTypeArguments[0] as Class<M>).kotlin
    }
}
```

**Comment by nEdAy** [comment]
> > @arnaudgiuliani
> > Are there any elegant approach that not pass class as a parameter to the activity?
> 
> Hope this isn't too late. You can try this:
> 
> ```
> 
> open class BaseFragment<M : ViewModel> : Fragment() {
>     val viewModel: M by lazy { getViewModel(viewModelClass()) }
> 
>     @Suppress("UNCHECKED_CAST")
>     private fun viewModelClass(): KClass<M> {
>         // dirty hack to get generic type https://stackoverflow.com/a/1901275/719212
>         return ((javaClass.genericSuperclass as ParameterizedType)
>             .actualTypeArguments[0] as Class<M>).kotlin
>     }
> }
> ```

There is a problem when using databinding at the same time.

**Comment by rasoulmiri** [comment]
@nEdAy if use ViewDataBinding use need change 0 to 1
because ViewModel is 2 in paramaeters
```
open class BaseFragment<B : ViewDataBinding, M : ViewModel> : Fragment() {
    val viewModel: M by lazy { getViewModel(viewModelClass()) }

    @Suppress("UNCHECKED_CAST")
    private fun viewModelClass(): KClass<M> {
        // dirty hack to get generic type https://stackoverflow.com/a/1901275/719212
        return ((javaClass.genericSuperclass as ParameterizedType)
            .actualTypeArguments[1] as Class<M>).kotlin
    }
}

```

**Comment by Adamshick012** [comment]
Is there an example of how this is implemented on a test Fragment? I am getting a No definition error when I use the above example. The only way I have gotten it to work was going around the lazy and doing a loadKoinModules(module{single{TestViewModel()}}) inside the TestFragment

**Comment by oth-libs** [comment]
Is there any possibility to do this but with **sharedViewModel**?

**Comment by LoAlex** [comment]
> > @arnaudgiuliani
> > Are there any elegant approach that not pass class as a parameter to the activity?
> 
> Hope this isn't too late. You can try this:
> 
> ```
> 
> open class BaseFragment<M : ViewModel> : Fragment() {
>     val viewModel: M by lazy { getViewModel(viewModelClass()) }
> 
>     @Suppress("UNCHECKED_CAST")
>     private fun viewModelClass(): KClass<M> {
>         // dirty hack to get generic type https://stackoverflow.com/a/1901275/719212
>         return ((javaClass.genericSuperclass as ParameterizedType)
>             .actualTypeArguments[0] as Class<M>).kotlin
>     }
> }
> ```

I have figured out by myself, quite similar with your approach , thank you for answer, happy coding :D

**Comment by tomek27** [comment]
I did it like this
```
abstract class BaseFragment<VM: BaseViewModel> : Fragment() {

    val viewModel: VM by lazy { getViewModel(clazz) }

    abstract var clazz: KClass<VM>

}
```
