### ISSUE TITLE
Dynamic parameter injection

### ISSUE THREAD

**Issue by aouerfelli** [Ekito/koin#59]
I'm using the `koin-android-architecture` version of the library. I've come across a situation where I'd like to use a parameter determined when an Activity/Fragment is created for a ViewModel. As an example:

`SomeActivity.kt`
```kt
class SomeActivity : BaseActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val id = getIdExtra() // From intent
        TODO("use id")
        val viewModel = getViewModel<SomeViewModel>()
        // ...
    }
}
```
`SomeViewModel.kt`
```kt
class SomeViewModel(
    private val repository: Repository, // Singleton
    private val id: Long
) : BaseViewModel() {
// ...
}
```

Is there a good way of doing this? I know that Kodein has [factory bindings](https://salomonbrys.github.io/Kodein/#_factory_binding), so I was wondering if there was something similar.

This issue is similar to #6 but I was wondering if there was a better method of achieving this now since that issue is relatively old.

**Comment by arnaudgiuliani** [comment]
Hello,

factory bindings are interesting and remind me the Android see injector from dagger (https://github.com/Ekito/koin/issues/56)

In the current version, you can use `setProperty()` to set a property that can be used later in injection:

```kotlin
class SomeActivity : BaseActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val id = getIdExtra() // From intent
        setProperty("id",id)
        val viewModel = getViewModel<SomeViewModel>()
        // ...
    }
}
```
with class

```kotlin
class SomeViewModel(
    private val repository: Repository, // Singleton
    private val id: Long
) : ViewModel()
```

you have to write your module entry with `getProperty`:

```kotlin
val module = applicationContext {
    bean { SomeViewModel(get(), getProperty("id")) }
}
```

I'm actually thinking about something like kodein factory bindings.

**Comment by aouerfelli** [comment]
Yeah that's what I went with, although I still think that dynamic factory bindings would be nice. Out of curiosity, if you're considering adding them, do you have an idea of how it would look like?

**Comment by arnaudgiuliani** [comment]
I 've add Koin parameters to release 0.9.0. 

you will be able to use parameters in your definition. Given class:

```kotlin
class MyPresenter(val activity : MyActivity)
```

We can use parameters to be injected with `by inject()`
```kotlin
val module = applicationContext {
   factory { params -> MyPresenter(params["activity"])}
}
```

Injecting the parameter:

```kotlin
class MyActivity : AppCompatActivity(){
   
   // Ask for MyPresenter injection and provide parameters
   val presenter : MyPresenter by inject( parameters = mapOf("activity" to this))
}
```

stay tuned👍

**Comment by pablobaldez** [comment]
It's a good aproach provides an activity instance in factory method using the getProperty method? Or could it give me some memory leaks?
Example code:
`
factory { getProperty("activity") }
factory { 
    // here we get the activity instance provided previously to make the factory of some another instance
    val activity = get<Activity>()
    LocalBroadcastManager.getInstance(activity)
 }
`

**Comment by pablobaldez** [comment]
It's a good aproach provides an activity instance in factory method using the getProperty method? Or could it give me some memory leaks?
Example code:
```kotlin
factory { getProperty("activity") } 
factory { 
    // here we get the activity instance provided previously to make the factory of some another instance 
    val activity = get<Activity>() 
    LocalBroadcastManager.getInstance(activity) 
}
```

**Comment by rafael-labela** [comment]
val presenter : MyPresenter by inject( parameters = mapOf("activity" to this)) nowadays throw an error since it is expecting a `ParametersDefinition`, how can we create them? the `DefinitionParameters` class has a private constructor, I haven't find a way to pass the proper lambda to achieve the `ParametersDefinition` required.

**Comment by desgraci** [comment]
val presenter : MyPresenter by inject( parameters = mapOf("activity" to this)) nowadays throw an error since it is expecting a ParametersDefinition, how can we create them? the DefinitionParameters class has a private constructor, I haven't find a way to pass the proper lambda to achieve the ParametersDefinition required.

**Comment by iRYO400** [comment]
Hi there! How is it going in 2.0?

**Comment by ZaydelEduard** [comment]
@iRYO400 [Look here](https://github.com/InsertKoinIO/koin/blob/master/koin-projects/docs/reference/koin-core/injection-parameters.md)
