### ISSUE TITLE
Inject using current Android Context

### ISSUE THREAD

**Issue by vpotvin** [Ekito/koin#60]
Hello I'm wondering simply if there is a way to inject an Activity or while using either it's context or the Application object to initialize the object.

So something like: 

```
class HomeActivity : Activity() {
    override val contextAwareObject by inject<ThisObjectNeedsContextInConstructor>()
}
```

I've tried using `get()` for the context in a module but it doesn't seem to be able to do the trick since it only has access to a Koin Context, not an Android one. I have seen an example using an `AndroidModule` but it seems I can't find an `AndroidModule` in the current version.

In particular I'm trying to inject access to my database, which is currently initialized and owned by the Application class. It needs an App context to start. So therefore my Activities have to know about it even though I'm using MVP. It would be really nice if when I inject my presenter I could also inject the presenter by constructor with the database object.

**Comment by caleb-allen** [comment]
So if I understand correctly, you need database access in, lets say, `HomeRepository`.

When you instantiate your dependencies, is that happening in your Application class? If so, you can inject the Application context directly from there. For example:

Your `HomeRepository` would look like:

    class HomeRepository(val appContext: Application, otherDependency: MiscDependency)
    . . . etc


And in your Application class, where Koin should be instantiated

    val myModule: Module = applicationContext {
        provide { MiscDependency() }
        provide { HomeRepository(this@Application, get()) }
    }

    startKoin(this, listOf(myModule))

Does this look like what you're asking for? With Koin, your activity shouldn't need a direct reference to the application context (for this purpose), and the database object should be able to have the application reference it needs directly.

**Comment by caleb-allen** [comment]
I think the wording of `koinContext` and `applicationContext` can be confusing, because Koin's `applicationContext` is different than Android's `Context`, which can be a part of an Android activity _or_ an application (the Application class is a subclass of Context), whereas a `koinContext` or Koin's `applicationContext` is Koin's way of referencing the Koin library and system, regardless of the platform.

**Comment by arnaudgiuliani** [comment]
Hello @vpotvin,

yes, there is no more `AndroidModule`.  The `applicationContext` function opens a lambda to describe a Koin application description module (as said @caleb-allen)

You can use the `androidApplication()` function to inject your Android `Application` context instance where you need. i.e:

Given a class that needs your App context:
```kotlin
class MyRepository(application : Application)
```
You can write it like this:
```kotlin
val yourModule = applicationContext {
    bean { MyRepository(androidApplication())}
}
```

If you need `Context` type, you can directly write `androidApplication().context`

**Comment by vpotvin** [comment]
Yes I think that is exactly what I am looking for. So if I have something like: 

```
val myModule = applicationContext {
    provide { myPresenter as myContract.Presenter }
    provide { MyObjectBox.builder().androidContext(androidApplication()).build() }
}
```

`provide` creates a singleton so it will only execute that builder once correct? Also is there a major difference between  `bean` and `provide`?

**Comment by arnaudgiuliani** [comment]
Yes, `provide {}` will manage a unique instance for you. `bean` can't' have extra binding with `bind`:

`provide { myPresenter } bind as myContract.Presenter::class`will bind definition on `myPresenter` type and `myContract.Presenter`. Whereas `provide { myPresenter as myContract.Presenter }` only bind the definition on `myContract.Presenter` type.

You can read more about the Koin DSL: http://insert-koin.io/docs/1.0/reference/koin-dsl/

But I see that people sometimes are confused about `provide` and `bean`. I will deprecate the `provide` keyword, to only have `bean` and `factory` keywords to declare your definitions.

**Comment by arnaudgiuliani** [comment]
I close the issue. Don"t hesitate to open a new one. Or try to contact us directly: https://insert-koin.io/docs/1.0/team/

Cheers.

**Comment by vpotvin** [comment]
Thank you for your help!
