### ISSUE TITLE
Injecting Room Databases

### ISSUE THREAD

**Issue by mvp-sales** [Ekito/koin#61]
Hello, I have an abstract class named `AppDatabase`, which inherits from `RoomDatabase`. I am trying to use Koin to provide `AppDatabase` to my repositories.

I have this line in one of my modules:
```kotlin
provide (isSingleton = true) { Room.databaseBuilder(androidApplication(), AppDatabase::class.java, Constants.DATABASE_NAME).build() }
```

When I run my app, I get this error:
`java.lang.RuntimeException: cannot find implementation for br.com.evologica.biblio_android.data.database.AppDatabase. AppDatabase_Impl does not exist`

Is there any way I can solve this problem?

**Comment by arnaudgiuliani** [comment]
Hello,

seems to be more a Room problem. Did you tried to just run `Room.databaseBuilder(androidApplication(), AppDatabase::class.java, Constants.DATABASE_NAME).build()` ?

**Comment by mvp-sales** [comment]
I did a quick search, and indeed, it seems to be a problem with Room. Thanks for your help.

**Comment by mdgarri** [comment]
> I did a quick search, and indeed, it seems to be a problem with Room. Thanks for your help.

Did you solved it? Can you share it pls if you did ?
