### ISSUE TITLE
Forwarding parameters

### ISSUE THREAD

**Issue by Bodo1981** [Ekito/koin#66]
**Koin 0.9.0 is really great**
Thanks for the parameter support when injecting dependencies. It is working great.

I have a small optimization for injecting with parameters.
It would be fantastic if we can forward this parameter map.

e.g.

```kotlin
class MyActivity : Activity() {
   val presenter: MyPresenter by inject(parameters = mapOf("activity" to this)
}

class MyPresenter(navigator: Navigator) {

}

class Navigator(activity: Activity) {

}
```
and the module looks like this
```kotlin
val myModule: Module = applicationContext {
   context("Screen") {
      bean { params -> MyPresenter(get()) }  // here we have the params with the activity 
      bean { params -> Navigator(params["activity"]) }  // BUT the activity is needed here (and here are params null)
   }
}
```

can you provide us with the possibillty to forward these params in the **get()** method, e.g

```kotlin
val myModule: Module = applicationContext {
   context("Screen") {
      bean { params -> MyPresenter(get(params)) }  // forward params in get(params)
      bean { params -> Navigator(params["activity"]) }  // so we can access the params here
   }
}
```

looking at the **get()** functions it should be possible
in the current version 0.9.0 you pass an emptyMap to the resolve functions.

```kotlin
inline fun <reified T : Any> get(): T = koinContext.resolveByClass(emptyMap())
inline fun <reified T : Any> get(name: String): T = koinContext.resolveByName(name, emptyMap())
```

maybe we can do something like this:

```kotlin
inline fun <reified T : Any> get(parameters: ParameterMap = emptyMap()): T = koinContext.resolveByClass(parameters)
inline fun <reified T : Any> get(name: String, parameters: ParameterMap = emptyMap()): T = koinContext.resolveByName(name, parameters)
```

What do you think about this?

**Comment by arnaudgiuliani** [comment]
Hello,

I will allow propagating parameters in next patch. You will be able to use `params.value` to pass in your `get()`DSL function.

like:

```kotlin
//with classes
class ComponentA(val componentC: ComponentC)
class ComponentB(val componentA: ComponentA)
```

```kotlin
 val simpleModule1 = applicationContext {
        bean { params -> ComponentA(params["this"]) }
        bean { params -> ComponentB(get(parameters = params.values)) }
    }
     
   // injecting ...
val componentB: ComponentB by inject(parameters = mapOf("this" to this))
```

**Comment by leonardoaramaki** [comment]
@arnaudgiuliani How this solves the OP issue? I mean, in your example:
`val componentB: ComponentB by inject(parameters = mapOf("this" to this))`

But in the `Navigator` class of the OP's example, it needs an activity so inside it's not possible to inject the activity from there because in `mapOf("this" to this))`, `this` is not an Activity but instead a Navigator. Did I missed something?

**Comment by arnaudgiuliani** [comment]
`val componentB: ComponentB by inject(parameters = mapOf("this" to this))`

means that you will store `this` with the key of `"this"`.  Which mean that you can reuse the value with this key in a definition: `bean { parms -> ... params["this"] ... }`

if your definition is using a compatible type of the forwarded parameter, it will be ok.

Did I respond to your question?

**Comment by jhandguy** [comment]
Hey @arnaudgiuliani!
`get(parameters = params.values)` does not work for me, I get a type mismatch _Parameters wanted and got Map<String, Any>_, any idea?

**Comment by jhandguy** [comment]
Got it!
Parameters is a typealias for `() -> Map<String, Any>` and not `Map<String, Any>`.
So the solution is to do `get { it.values }` =)

**Comment by arnaudgiuliani** [comment]
yeah, it's a lambda. This can be a bit tricky.

**Comment by z3ntu** [comment]
Hello. (while waiting for my kotlin slack invitation I'm writing here)

I have the following module defined:
```kotlin
val nextNewsModule = module {
    single { (acc: SingleSignOnAccount) -> provideAuthenticationInterceptor(acc) }
    single { params -> provideHttpClient(get { params }) }
    single { (acc: SingleSignOnAccount) -> provideRetrofit(get { params }, acc) }
    single { params -> provideNewsService(get { params }) }
    single<NewsRepository> { params -> NewsRepositoryImpl(get { params }) }
    viewModel { params -> NewsViewModel(get { params }) }
}
```
and getting called by
```kotlin
private val vm: NewsViewModel by viewModel { parametersOf(SingleSignOnAccount("a", "b", "c", "d")) }
```
The problem before adding all the `params ->` was that the "downstream dependencies" didn't get the required `SingleSignOnAccount` instance and Koin failed to inject.
Now I think I just need to pass the params object through the `provideRetrofit` line (so it reaches the `provideAuthenticationInterceptor`) but with the extra `(acc: SingleSignOnAccount)` parameter I don't know the syntax to make this working.

I got the `params -> ... get { params }` from [here](https://github.com/InsertKoinIO/koin/blob/master/koin-projects/koin-test/src/test/kotlin/org/koin/test/core/ParametersPropagationTest.kt#L17) and it would also be nice if such an example was on the website.

**Comment by z3ntu** [comment]
I've got it working now by using 
```kotlin
single { params -> provideRetrofit(get { params }, params.component1()) }
```

Such an example should still be put on the website though. Thanks for creating Koin!
