### ISSUE TITLE
Release context doesn't release viewModels

### ISSUE THREAD

**Issue by gpulido** [Ekito/koin#70]
Hello,
In my application I have the concept of "tournament selected" that acts as a container where several objects are created in (they have a reference to the tournament uuid where they belong).
The current tournament uuid selected is stored as a preference on the SharedPreferences manager.
This preference is loaded and used as a koin property using the koin setProperty(CURRENT_TOURNAMENT_ID, prefManager.currenttournament)

Then this property is used on viewmodel constructors and is injected by koin using module definition.
For example I have a 
```Kotlin
RankingRoundViewModel(contenderId: String, tourId: String, viewModelDao:ContenderDao) 
```
That is declared in a koin module by:

```kotlin
viewModel { params -> RankingRoundViewModel(params[EXTRA_RANKING_ROUND_ID], getProperty(CURRENT_TOURNAMENT_ID), get()) }
```
And injected on the rankingRoundFragment:

```Kotlin
class RankingRoundDetailFragment : 
DetailObjectDataBindingFragment<RankingRoundDetailViewBinding>(){

    val viewModel: RankingRoundViewModel by viewModel{ mapOf(Properties.EXTRA_RANKING_ROUND_ID to (getKey<RankingRoundDetailKey>()?.id?:EmptyUUID)) }
}
```
This is working fine.
Now I want to allow the user to change the selected tournament, so I decided to create a "TournamentContext" on the koin module and put the viewmodel inside:

```Kotlin
applicationContext {
bean { SharedPrefManager(get()) }

     context("TournamentContext")
     {
        viewModel { params -> RankingRoundViewModel(params[EXTRA_RANKING_ROUND_ID], getProperty(CURRENT_TOURNAMENT_ID), get()) }
    }
}
```

And drop the context when the user selects a new tournament using the following code:
```Kotlin
     releaseContext("TournamentContext")
     prefManager.defaultTournament = model.tournament.uuid
     setProperty(Properties.CURRENT_TOURNAMENT_ID, prefManager.defaultTournament)

```
I checked and the code is executed
The problem is that when I open again the RankingRoundDetailFragment the viewModel is not being rebuild and is using the old viewmodel with the old property.

What I'm doing wrong?

Thank you in advance

**Comment by arnaudgiuliani** [comment]
Hello,

first, context is not needed when using factory providers. `factory` or `viewModel` instances are not kept by Koin container (a new instance is created each time we ask for it).

By default, you will use the Activity ViewModel in your Fragment. This means that by using 
`val viewModel: RankingRoundViewModel by viewModel` in your fragment, you are using the Activity instance of it.

You can force to create a new one by passing `fromActivity = false` in parameters of `by viewModel()`

After this, check that your Activity is really reloading. Because a ViewModel will be kept for your activity until it has been destroyed.

**Comment by gpulido** [comment]
Hello,
I added the fromActivity = false and now it is retrieving the updated property. Thank you.

Just as a suggestion, maybe the viewmodel factory should have the fromactivity = false by default, or add the capability of configuring it on the initkoin call.
As I'm using one Activity => multiple fragments pattern, I always want the viewmodels to be inflated by the fragment using the fragment context, so it would be nice to be able to have that behaviour by default or globally defined.
Regards

**Comment by arnaudgiuliani** [comment]
Yes you are perfectly right. 

I think about updating the API with :

- `by viewModel()` - to inject a new instance of the VM (Activity or Fragment)
- `by sharedViewModel()` - in Fragments, to reuse VM from Activity

I close the issue. Stay tuned for the `0.9.1` then ;)
