### ISSUE TITLE
Dynamic inject by name doesn't work in 0.9.+

### ISSUE THREAD

**Issue by vnesek** [Ekito/koin#72]
Hi,

I was using following code in 0.8.2 to create Fragments by name:

```
// Module ( class FooBarFragment : android.app.Fragment )
factory("fooBar")  { FooBarFragment() }

// In activity
val fragment = inject<Fragment>("fooBar").value
```
In 0.9.0 this fails:

```
java.lang.IllegalStateException: 
Stack resolution error : was Factory[name='fooBar', class=org.foobar.FooBarFragment] 
but should be android.app.Fragment
at org.koin.KoinContext.resolveInstance(KoinContext.kt:95)
```

I can workaround it by changing module definitions to:

```
factory("fooBar")  { FooBarFragment() as Fragment }
```
I would assume that inject function consider candidate's base classes when looking for dependency but expect exact type. Is this expected behaviour?

**Comment by arnaudgiuliani** [comment]
Hello,

for interface and implementation, it should be Ok. But I think, the stack resolution has a regression :/

Stay on 0.8.2.
I'm on it

**Comment by arnaudgiuliani** [comment]
Hello @vnesek,

release `0.9.1-alpha-7` should fixed your need. Let me know if it's ok.

**Comment by arnaudgiuliani** [comment]
I had some more tests. Should be ok. Give a try with last alpha. I close the issue.

**Comment by vnesek** [comment]
Works for me at version 0.9.1.
