### ISSUE TITLE
Build problem after version update (from 0.9.0-alpha-11 to 0.9.0)

### ISSUE THREAD

**Issue by shrpereira** [Ekito/koin#73]
The use case discussed on issue #56 stop working after updating the library to the 0.9.0 stable version.

The error I'm having is the following:
```
Error:(19, 38) Type inference failed: inline fun <reified T : ViewModel> LifecycleOwner.viewModel(fromActivity: Boolean = ..., key: String? = ..., name: String? = ..., parameters: ParameterMap /* = Map<String, Any> */ = ...): Lazy<T>
cannot be applied to
receiver: BaseActivity<ViewModelType>  arguments: (KClass<ViewModelType>)
```

For the following code, that is working on 0.9.0-alpha-11 version:
```
@SuppressLint("Registered")
open class BaseActivity<out ViewModelType : BaseViewModel>(clazz: KClass<ViewModelType>) :
        AppCompatActivity() {

    val viewModel: ViewModelType by viewModel(clazz)

```

**Comment by arnaudgiuliani** [comment]
Hello,

As I pointed at the end of the issue, you should use the `by viewModelByClass(clazz)` to allow using KClass<*>. Else you will use the type inference parameters.

Let me know if it's better.

**Comment by arnaudgiuliani** [comment]
I close the issue. I think you just have to use the right function API, which has been named `getViewModelByClass()` and `by viewModelByClass()`.

**Comment by sola1tmy** [comment]
Is it possible to inject viewModel this way in 2.0.0-beta-1? I can't find method **viewModelByClass** in 2.0.0-beta-1.
