### ISSUE TITLE
Can't create bean Factory[class=com.example.androidarch.view.users.UserContract.Presenter] due to error

### ISSUE THREAD

**Issue by rogcg** [Ekito/koin#80]
So, I've been following the [weather sample](https://github.com/Ekito/koin-samples/tree/master/samples/android-weatherapp), and I've faced this error when creating a new feature.

This is my **app_module.kt** file:

```
val myModule = applicationContext {

    factory { params -> UserPresenter(get(), get(), params[USER_VIEW]) as UserContract.Presenter}
    bean { UserRepositoryImpl(get()) as UserRepository }
}

val rxModule = applicationContext {
    // provided components
    bean { ApplicationSchedulerProvider() as SchedulerProvider }
}

object Params {
    const val USER_VIEW = "USER_VIEW"
}  

// Gather all app modules
val myApp = listOf(myModule, rxModule)
```

I have a file called **UserRepository.kt** that looks like this:

```
interface UserRepository {
    fun fetchUsers(): Single<PeopleResponse>
}

class UserRepositoryImpl(private val userDataSource: UserDataSource): UserRepository {

    override fun fetchUsers(): Single<PeopleResponse> {
...
```

and my presenter (**UserPresenter.kt**) looks like this:

```
class UserPresenter(
        val userRepository: UserRepository,
        val schedulerProvider: SchedulerProvider,
        override var view: UserContract.View):
        AbstractPresenter<UserContract.View, UserContract.Presenter>(),
        UserContract.Presenter{
...
```

Also the **UserDataSource** is just a interface with the endpoints:

```
interface UserDataSource {
    @GET("/")
    @Headers("Content-type: application/json")
    fun fetchPeople(@Query("results") results: Int, @Query("nat") nat: String) : Call<PeopleResponse>
}
```

In my *activity* I've been injecting the presenter like this:

`override val presenter : UserContract.Presenter by inject { mapOf(USER_VIEW to this) }`

just as in other activities, using the map to associate the view.

However, when I execute my **UserActivity**, I get the following error:

> Caused by: org.koin.error.BeanInstanceCreationException: Can't create bean Factory[class=com.example.androidarch.view.users.UserContract.Presenter] due to error :
                                                                       	org.koin.error.BeanInstanceCreationException: Can't create bean Bean[class=com.example.androidarch.repository.UserRepository] due to error :
                                                                       	org.koin.error.NoBeanDefFoundException: No definition found to resolve type 'com.example.androidarch.repository.UserDataSource'. Check your module definition

Any ideas of what might be happening? Thanks in advance.

**Comment by arnaudgiuliani** [comment]
Hello,

none of your modules provide any bean definition for type `UserDataSource`. Where do you define it?

**Comment by rogcg** [comment]
Indeed. I forgot to add it in my list of modules when starting koin. Thanks for the help.
