### ISSUE TITLE
Availability For JAVA

### ISSUE THREAD

**Issue by BismeetSingh** [Ekito/koin#81]
Can this be ported to java. Seems better than the dagger hanging over my head.

**Comment by arnaudgiuliani** [comment]
Hello,

the interest of Koin is in its ease of use. Check the gists where I put Koin for a Java app:

https://gist.github.com/arnaudgiuliani/446e0d8ee79f4bda38b3057b01098f2e

**Comment by jablonskipj** [comment]
I have used it in java. But injection was not done by java code. I have implemented some kind of proxy Kotlin class that I extended in java. It looked like this:

```
class InjectClass {
  val presenter: Presenter by inject()
}

```
and then I have extended this class by java:

```
class InjextExtension extends InjectClass {
    public void fun() {
     ///this is how we access our dependency in java
      getPresenter();
   }
}
```

**Comment by fredy-mederos** [comment]
Here there are some utility functions to inject koin components and properties in java.
Basically this utility functions remove the `reified` types and replace them for java class.

Check it out:
https://gist.github.com/fredy-mederos/b74e8c2f2ca2f0f5d5910bcb694cbdbf

**Comment by jablonskipj** [comment]
@fredy-mederos looks like a very good solution. Could you also provide a snippet that shows how injection looks on java site?

**Comment by fredy-mederos** [comment]
Example in java:
```java
MyManager myManager = KoinJavaUtils.get(MyManager.class);
```

You can use it in attributes and you can also use the function `KoinJavaUtils.inject` to get a Lazy object.

I wrote those utility functions to migrate from dagger2 some Android java activities that I can't _convert_ to kotlin and it works good!

**Comment by arnaudgiuliani** [comment]
Good job @fredy-mederos!  Could be a good contribution and blog post about it 👍

**Comment by fredy-mederos** [comment]
Thanks!
I'll create some test cases and include them all in the koin-core via PR
It is a good idea the blog post thing... I'll prepare a draft ;)

**Comment by arnaudgiuliani** [comment]
I close the issue here to continue on PR. Thanks
