### ISSUE TITLE
Need a new bean definition which behaves as single, but releases itself once become unused

### ISSUE THREAD

**Issue by BimuratMukhtar** [Ekito/koin#881]
**Is your feature request related to a problem? Please describe.**
At the moment we have bean definitions like: single, factory, scope. But what I need: a bean definition which behaves as single while it is used, but releases itself once it will become unused by any object. It is something similar to in java's garbage  colleciton which removes all unused resources automatically.

**Describe the solution you'd like**
suggested name of bean definition: weakSingle {  }

**Describe alternatives you've considered**
Do not have alternatives

**Target Koin project**
any project

**Comment by arnaudgiuliani** [comment]
Could be interesting to see how we can prototype this, inside our InstanceFactory component.
