### ISSUE TITLE
Koin.useContextIsolation

### ISSUE THREAD

**Issue by Shakezulla57** [Ekito/koin#91]
Looking at the docs for [context isolation](https://insert-koin.io/docs/1.0/reference/contexts/#context-isolation) but not seeing `useContextIsolation` property available on the `Koin` class. Using `0.9.1`

**Comment by arnaudgiuliani** [comment]
Hello,

context isolation is now active by default. `useContextIsolation` has been removed to  to let the context resolution being isolated.
