### ISSUE TITLE
DryRun can't resolve androidApplication()

### ISSUE THREAD

**Issue by skimarxall** [Ekito/koin#95]
Hi,

After adding the DryRun test I am getting this error

```
org.koin.error.NoBeanDefFoundException: No definition found to resolve type 'android.app.Application'. Check your module definition
```
This is my definition

```
val androidModule = applicationContext {

    bean { androidApplication().resources }
    ...
}
```

Should I provide a mock AndroidApplication or what is the best way to solve that?
Thanks :)

**Comment by arnaudgiuliani** [comment]
Hello, yes you need to provide a mock for `Application`.

You can do it, when starting Koin in test with the keyword `with` behind `startKoin`:

```kotlin
startKoin(modules) with mock(Application::class.java)
```

**Comment by skimarxall** [comment]
Thanks for the clarification.
I am still having issues since the dry run is initializing all the classes and some of them uses the context. Since it's mock I get into NullPointer and other problems.

I tried to run then in an instrumentation test. This helped.
